#数据源配置 spring.elasticjob.zookeeper
env: local
server:
  port: 8080
  servlet:
    context-path: /wms
spring:
  application:
    name: wms
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 5000MB
  #邮箱配置
  mail:
    host: smtp.qiye.aliyun.com
    port: 465
    username: no-reply@sifubuy.com
    password: xportcn@0730
    personal: Sifubuy
  redis:
    ##redis 单机环境配置
    host: localhost
    port: 6379
    #    password: pandaponIM333
    database: 0
    ssl: false
    ##redis 集群环境配置
    #cluster:
    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    #  commandTimeout: 5000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wms?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

# 系统设置
system:
  # 新建用户默认密码
  defaultPassword: 123456

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.sifubuy.wms.dao.po

#oss配置
oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  access-key: LTAI5tEkqEZn342tsxLamrwF
  secret-key: VIlgrT9D890uNTRrFaj5bOHf4v32Nl
  bucket-name: pandapon-buy-dev


logging:
  config: classpath:log/logback.xml

business:
  delivery:
    freezeDays: 45
    expireDays: 60






